# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Endpoint(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    org_id: Annotated[
        str,
        Field(
            alias="orgId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    name: str
    paused: bool
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]


class CreatedEndpoint(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    org_id: Annotated[
        str,
        Field(
            alias="orgId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    name: str
    paused: bool
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    ingest_url: Annotated[AnyUrl, Field(alias="ingestUrl")]


class DeletedEndpoint(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    deleted_at: Annotated[AwareDatetime, Field(alias="deletedAt")]


class RevokedProviderSecret(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    revoked_at: Annotated[AwareDatetime, Field(alias="revokedAt")]


class ReplayDestination(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    org_id: Annotated[
        str,
        Field(
            alias="orgId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    url: str
    label: str | None
    status: str
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    last_validated_at: Annotated[AwareDatetime | None, Field(alias="lastValidatedAt")]
    ordered: bool
    disabled_at: Annotated[AwareDatetime | None, Field(alias="disabledAt")]


class CreatedReplayDestination(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    org_id: Annotated[
        str,
        Field(
            alias="orgId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    url: str
    label: str | None
    status: str
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    last_validated_at: Annotated[AwareDatetime | None, Field(alias="lastValidatedAt")]
    ordered: bool
    disabled_at: Annotated[AwareDatetime | None, Field(alias="disabledAt")]
    signing_secret: Annotated[str | None, Field(alias="signingSecret")] = None


class ReplayDestinationDeleted(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    deleted_at: Annotated[AwareDatetime, Field(alias="deletedAt")]


class RotatedSigningSecret(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    destination_id: Annotated[
        str,
        Field(
            alias="destinationId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    key_id: Annotated[
        str,
        Field(
            alias="keyId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    signing_secret: Annotated[str, Field(alias="signingSecret")]


class SigningSecretMetadata(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    status: str
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]


class Subscription(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    org_id: Annotated[
        str,
        Field(
            alias="orgId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    source_endpoint_id: Annotated[
        str,
        Field(
            alias="sourceEndpointId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    destination_id: Annotated[
        str,
        Field(
            alias="destinationId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    provider: str | None
    event_types: Annotated[list[str], Field(alias="eventTypes")]
    require_verified: Annotated[bool, Field(alias="requireVerified")]
    enabled: bool
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]


class SubscriptionDeleted(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]


class AuthContext(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    org_id: Annotated[str, Field(alias="orgId", min_length=1)]
    user_id: Annotated[str | None, Field(alias="userId")] = None
    scopes: list[str]


class VerificationResult1(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ok: Literal[True]
    key_id: Annotated[str, Field(alias="keyId")]
    scheme: str
    authenticity: str | None = None


class Reason(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["MISSING_HEADER"]
    header: str
    scheme: str


class Reason1(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["MALFORMED_SIGNATURE"]
    detail: str
    scheme: str


class Reason2(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["UNSUPPORTED_SCHEME"]
    observed_headers: Annotated[list[str], Field(alias="observedHeaders")]


class Reason3(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["KEY_FETCH_FAILED"]
    scheme: str


class Reason4(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["TIMESTAMP_TOO_OLD"]
    skew_seconds: Annotated[float, Field(alias="skewSeconds")]
    tolerance_seconds: Annotated[float, Field(alias="toleranceSeconds")]


class Reason5(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["TIMESTAMP_IN_FUTURE"]
    skew_seconds: Annotated[float, Field(alias="skewSeconds")]
    tolerance_seconds: Annotated[float, Field(alias="toleranceSeconds")]


class Reason6(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["NO_MATCHING_KEY"]
    keys_tried: Annotated[int, Field(alias="keysTried", ge=0, le=9007199254740991)]


class Reason7(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["WRONG_SECRET"]
    confidence: str


class Reason8(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["RAW_BODY_MODIFIED"]
    confidence: str
    evidence: str | None = None


class Reason9(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["PROXY_MUTATED_BYTES"]
    confidence: str


class Reason10(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Literal["SIGNATURE_MISMATCH"]


class VerificationResult2(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ok: Literal[False]
    reason: (
        Reason
        | Reason1
        | Reason2
        | Reason3
        | Reason4
        | Reason5
        | Reason6
        | Reason7
        | Reason8
        | Reason9
        | Reason10
    )


class VerificationResult(RootModel[VerificationResult1 | VerificationResult2]):
    root: VerificationResult1 | VerificationResult2


class EndpointsListResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    items: list[Endpoint]
    next_cursor: Annotated[str | None, Field(alias="nextCursor")]


class EventsGetPayloadResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    content_type: Annotated[str | None, Field(alias="contentType")]
    bytes: Annotated[int, Field(ge=0, le=9007199254740991)]
    body_base64: Annotated[str, Field(alias="bodyBase64")]


class Lag(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    backlog_count: Annotated[
        int, Field(alias="backlogCount", ge=0, le=9007199254740991)
    ]
    head_lag_ms: Annotated[
        int | None, Field(alias="headLagMs", ge=0, le=9007199254740991)
    ] = None


class AuditVerifyResponse1(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ok: Literal[True]
    rows_verified: Annotated[
        int, Field(alias="rowsVerified", ge=0, le=9007199254740991)
    ]


class Break(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    kind: str
    seq: Annotated[int, Field(gt=0, le=9007199254740991)]
    detail: str


class AuditVerifyResponse2(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ok: Literal[False]
    rows_verified: Annotated[
        int, Field(alias="rowsVerified", ge=0, le=9007199254740991)
    ]
    break_: Annotated[Break, Field(alias="break")]


class AuditVerifyResponse(RootModel[AuditVerifyResponse1 | AuditVerifyResponse2]):
    root: AuditVerifyResponse1 | AuditVerifyResponse2


class ReplayDestinationsListResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    items: list[ReplayDestination]


class ReplayDestinationsListSigningSecretsResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    items: list[SigningSecretMetadata]


class SubscriptionsListResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    items: list[Subscription]


class EndpointsCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: Annotated[str, Field(max_length=200, min_length=1)]


class EndpointsAddProviderSecretRequest(BaseModel):
    """
    The server additionally validates the secret shape per provider (e.g. a Standard-Webhooks secret must be base64 key material); a malformed value is rejected with 400 VALIDATION_ERROR.
    """

    model_config = ConfigDict(
        extra="ignore",
    )
    provider: str
    label: Annotated[str | None, Field(max_length=200, min_length=1)] = None
    secret: Annotated[str, Field(max_length=4096, min_length=1)]
    kind: str | None = "signing_secret"


class Target(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    kind: Literal["localhost-tunnel"]
    session_id: Annotated[str, Field(alias="sessionId", min_length=1)]


class Target1(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    kind: Literal["destination"]
    destination_id: Annotated[
        str,
        Field(
            alias="destinationId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]


class EventsReplayRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    target: Target | Target1
    idempotency_key: Annotated[str, Field(alias="idempotencyKey", min_length=1)]


class ReplayDestinationsCreateRequest(BaseModel):
    """
    `url` must be a public HTTPS URL (no IP-literal host, credentials, disallowed port, or bare hostname); the server rejects a non-conforming URL with 400 VALIDATION_ERROR.
    """

    model_config = ConfigDict(
        extra="ignore",
    )
    url: Annotated[str, Field(max_length=2048, min_length=1)]
    label: Annotated[str | None, Field(max_length=200, min_length=1)] = None


class ReplayDestinationsSetOrderedRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ordered: bool


class SubscriptionsCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    source_endpoint_id: Annotated[
        str,
        Field(
            alias="sourceEndpointId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    destination_id: Annotated[
        str,
        Field(
            alias="destinationId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    provider: str | None = None
    event_types: Annotated[
        list[str] | None, Field(alias="eventTypes", max_length=100)
    ] = None
    require_verified: Annotated[bool | None, Field(alias="requireVerified")] = None


class Error(BaseModel):
    """
    The JSON error envelope for capability faults.
    """

    model_config = ConfigDict(
        extra="ignore",
    )
    error: Annotated[str, Field(description="A stable capability-error code.")]
    message: Annotated[str, Field(description="A human-readable description.")]


class EventSummary(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    org_id: Annotated[
        str,
        Field(
            alias="orgId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    endpoint_id: Annotated[
        str,
        Field(
            alias="endpointId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    received_at: Annotated[AwareDatetime, Field(alias="receivedAt")]
    provider: str | None
    dedup_key: Annotated[str, Field(alias="dedupKey")]
    dedup_strategy: Annotated[str, Field(alias="dedupStrategy")]
    verified: bool
    verification_state: Annotated[str | None, Field(alias="verificationState")] = None


class Event(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    org_id: Annotated[
        str,
        Field(
            alias="orgId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    endpoint_id: Annotated[
        str,
        Field(
            alias="endpointId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    received_at: Annotated[AwareDatetime, Field(alias="receivedAt")]
    provider: str | None
    dedup_key: Annotated[str, Field(alias="dedupKey")]
    dedup_strategy: Annotated[str, Field(alias="dedupStrategy")]
    verified: bool
    verification_state: Annotated[str | None, Field(alias="verificationState")] = None
    payload_r2_key: Annotated[str, Field(alias="payloadR2Key")]
    payload_bytes: Annotated[
        int, Field(alias="payloadBytes", ge=0, le=9007199254740991)
    ]
    content_type: Annotated[str | None, Field(alias="contentType")]
    method: str | None = None
    headers: list[list[Any]]
    provider_event_id: Annotated[str | None, Field(alias="providerEventId")]
    external_id: Annotated[str | None, Field(alias="externalId")]
    verification: VerificationResult | None


class AddedProviderSecret(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    provider: str
    status: str


class ProviderSecretSummary(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    provider: str
    status: str
    label: str | None
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]


class DeliveryAttempt(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    org_id: Annotated[
        str,
        Field(
            alias="orgId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    event_id: Annotated[
        str,
        Field(
            alias="eventId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    target: str
    idempotency_key: Annotated[str | None, Field(alias="idempotencyKey")]
    status: str
    status_code: Annotated[int | None, Field(alias="statusCode")]
    attempt: Annotated[int, Field(gt=0, le=9007199254740991)]
    error: str | None
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]


class Delivery(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]
    event_id: Annotated[
        str,
        Field(
            alias="eventId",
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
        ),
    ]
    destination_id: Annotated[str | None, Field(alias="destinationId")]
    subscription_id: Annotated[str | None, Field(alias="subscriptionId")]
    status: str
    status_code: Annotated[int | None, Field(alias="statusCode")]
    attempt: Annotated[int, Field(gt=0, le=9007199254740991)]
    error: str | None
    next_retry_at: Annotated[AwareDatetime | None, Field(alias="nextRetryAt")]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]


class EndpointsListProviderSecretsResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    items: list[ProviderSecretSummary]


class EventsListResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    items: list[EventSummary]
    next_cursor: Annotated[str | None, Field(alias="nextCursor")]
    head_cursor: Annotated[str | None, Field(alias="headCursor")] = None


class EventsTailResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    items: list[EventSummary]
    next_cursor: Annotated[str | None, Field(alias="nextCursor")]
    head_cursor: Annotated[str | None, Field(alias="headCursor")] = None
    caught_up: Annotated[bool | None, Field(alias="caughtUp")] = None
    lag: Lag | None = None


class DeliveriesListResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    items: list[Delivery]
    next_cursor: Annotated[str | None, Field(alias="nextCursor")]
