// Adyen standard (payment) webhooks. The signature is not in a header — each entry of the JSON body's
// `notificationItems` array carries its own `NotificationRequestItem.additionalData.hmacSignature`
// (base64). The signed message is 8 fields of THAT item joined by a plain colon, absent fields as the
// empty string, with NO escaping and NO sorting (escaping belongs to the legacy HPP signature, a
// different scheme from the same vendor — conflating them is a documented way to get this wrong). The
// key is the Customer-Area HMAC key HEX-DECODED, not its ASCII characters. HMAC-SHA256, no timestamp.
//
// WHY THIS IS BESPOKE AND NOT A CONFIG ROW. It used to be one, addressing `notificationItems.0.…`,
// because a declarative `jsonField` path is fixed and cannot iterate. Adyen batches: production
// traffic carries several items per request. Verifying index 0 alone left items 1..N neither verified
// nor rejected, so a request pairing one authentic item with any number of forged ones was reported
// `ok` and the caller went on to process all of them. A signature check that can be walked past by
// appending to an array is not providing the property it exists for. Iteration is precisely what a
// config row cannot express, which is what makes this bespoke.
//
// EVERY item must verify, under the SAME key. Requiring one key for the whole request keeps `keyId`
// unambiguous and is the stricter reading; a batch is generated by one merchant account at one moment,
// so mixed keys within a single request are not a shape Adyen produces. If that ever changes, relax
// this deliberately — do not let it decay into per-item key search by accident.
//
// ⚠️ KNOWN, PRE-EXISTING: the colon join is not injective. A separator with no escaping means adjacent
// fields can be re-partitioned without changing the signed bytes —
//   merchantReference "REF:1130" + amount.value 1130   -> "…:REF:1130:1130:EUR:…"
//   merchantReference "REF"      + amount.value "1130:1130" -> "…:REF:1130:1130:EUR:…"
// so one Adyen-issued signature is valid for both readings, and `merchantReference` is usually
// merchant-controlled. This is the scheme as we implement it, not something this adapter introduced —
// the config row it replaces joined the same fields with the same literal colons.
//
// Whether that is Adyen's scheme or OUR bug is genuinely open. The "no escaping" rule is asserted from
// a self-consistent KAT plus Adyen's published worked example, and that example's values contain no
// colon — so our only external oracle is silent on exactly the detail in question. If Adyen does
// escape `\` and `:` in notification HMACs (it demonstrably does for the legacy HPP signature), then
// every payload carrying a colon is a FALSE REJECT today. Settle it against Adyen's own documentation
// before changing anything here: deviating from the provider on a guess turns a latent ambiguity into
// live rejected traffic.

import { bytesToB64, hexToBytes, hmacSha256, timingSafeEqual, utf8Encoder } from "../../bytes";
import type { VerifyAdapter, VerifyInput } from "../../adapter";
import { verificationFailed, verificationOk, type VerificationResult } from "../../verification";
import { PROVIDER_TOLERANCE_SECONDS } from "../config";
import { oversizeBodyFailure } from "../shared";

/** The 8 signed fields, in Adyen's order. */
const SIGNED_FIELDS = [
  "pspReference",
  "originalReference",
  "merchantAccountCode",
  "merchantReference",
  "amount.value",
  "amount.currency",
  "eventCode",
  "success",
] as const;

/** Read a dotted path, stringifying scalars. Absent/null/object -> "" (Adyen's empty-field rule). */
function scalarAt(item: unknown, path: string): string {
  let cur: unknown = item;
  for (const key of path.split(".")) {
    if (typeof cur !== "object" || cur === null) return "";
    cur = (cur as Record<string, unknown>)[key];
  }
  if (cur === null || cur === undefined) return "";
  if (typeof cur === "string") return cur;
  if (typeof cur === "number" || typeof cur === "boolean") return String(cur);
  return ""; // arrays/objects are not scalar fields; treat as absent rather than JSON-stringifying
}

interface ParsedItem {
  readonly message: Uint8Array;
  readonly signature: string;
}

/**
 * Every notification item, each with its own signed message and its own claimed signature.
 * `null` means the body is not a shape we can verify at all — reported MALFORMED, never skipped.
 */
function parseItems(rawBody: Uint8Array): ParsedItem[] | null {
  let body: unknown;
  try {
    body = JSON.parse(new TextDecoder().decode(rawBody));
  } catch {
    return null;
  }
  if (typeof body !== "object" || body === null) return null;
  const items = (body as Record<string, unknown>).notificationItems;
  // An empty array is NOT "nothing to check, therefore fine" — there is no authentic content in it,
  // and returning ok would be a pass over an empty set.
  if (!Array.isArray(items) || items.length === 0) return null;

  const parsed: ParsedItem[] = [];
  for (const entry of items) {
    if (typeof entry !== "object" || entry === null) return null;
    const item = (entry as Record<string, unknown>).NotificationRequestItem;
    if (typeof item !== "object" || item === null) return null;
    const signature = scalarAt(item, "additionalData.hmacSignature");
    if (signature === "") return null; // an item without a signature cannot be verified
    parsed.push({
      message: utf8Encoder.encode(SIGNED_FIELDS.map((f) => scalarAt(item, f)).join(":")),
      signature,
    });
  }
  return parsed;
}

export function makeAdyenAdapter(): VerifyAdapter {
  const toleranceSeconds = PROVIDER_TOLERANCE_SECONDS.adyen;

  async function verify(input: VerifyInput): Promise<VerificationResult> {
    const oversize = oversizeBodyFailure("adyen", input.rawBody);
    if (oversize !== null) return oversize;

    const items = parseItems(input.rawBody);
    if (items === null) {
      return verificationFailed({
        code: "MALFORMED_SIGNATURE",
        detail:
          "body is not an Adyen notification: expected a non-empty notificationItems array, each entry carrying NotificationRequestItem.additionalData.hmacSignature",
        scheme: "adyen",
      });
    }

    let sawUsableSecret = false;
    for (let i = 0; i < input.secrets.length; i++) {
      const key = hexToBytes(input.secrets[i]!);
      if (key === null) continue; // the Adyen key is hex; a non-hex secret is for another provider
      sawUsableSecret = true;

      // EVERY item, not the first. `every` short-circuits, so a forged item ends this key's attempt —
      // but it ends it as a failure, never as a partial pass.
      let allVerified = true;
      for (const item of items) {
        const expected = bytesToB64(await hmacSha256(key, item.message));
        if (!timingSafeEqual(utf8Encoder.encode(expected), utf8Encoder.encode(item.signature))) {
          allVerified = false;
          break;
        }
      }
      if (allVerified) return verificationOk(`secret_${i}`, "adyen");
    }

    if (!sawUsableSecret) return verificationFailed({ code: "NO_MATCHING_KEY", keysTried: 0 });
    return verificationFailed({ code: "SIGNATURE_MISMATCH" });
  }

  // No header carries the signature; it is inside the body. Kept as "" for parity with the config row
  // this replaces — `detectScheme` cannot identify Adyen from headers, and never could.
  return { scheme: "adyen", signatureHeader: "", toleranceSeconds, verify };
}
