// AUTO-GENERATED by gen_vo.py — narration cues + music bed for the promo film.
// Narration: Piper TTS (en_US-ryan-high, MIT). Music: numpy-synthesized (owned).
// Placements are non-overlapping + scene-anchored (see the brief §6.2 / §7).

export interface VoCue {
  src: string;
  from: number;
  durationInFrames: number;
}

export const VO_CUES: VoCue[] = [
  { src: "audio/vo/vo_01.mp3", from: 8, durationInFrames: 46 },
  { src: "audio/vo/vo_02.mp3", from: 210, durationInFrames: 183 },
  { src: "audio/vo/vo_03.mp3", from: 401, durationInFrames: 86 },
  { src: "audio/vo/vo_04.mp3", from: 495, durationInFrames: 170 },
  { src: "audio/vo/vo_05.mp3", from: 673, durationInFrames: 145 },
  { src: "audio/vo/vo_06.mp3", from: 826, durationInFrames: 107 },
  { src: "audio/vo/vo_07.mp3", from: 941, durationInFrames: 218 },
  { src: "audio/vo/vo_08.mp3", from: 1167, durationInFrames: 200 },
  { src: "audio/vo/vo_09.mp3", from: 1470, durationInFrames: 140 },
  { src: "audio/vo/vo_10.mp3", from: 1618, durationInFrames: 103 },
];

export const MUSIC_SRC = "audio/music/bed.mp3";
