/**
 * Every provider the verification registry can check — slug (for the brand mark) and display name.
 *
 * This is DATA, not a claim someone typed: it is generated from `PROVIDERS` in
 * `@webhook-co/webhooks-spec`, run through the same `providerDisplayName` the dashboard uses.
 * `provider-wall.test.tsx` re-derives it from that registry and fails if the two diverge — add the
 * 143rd adapter and the test tells you to regenerate this file.
 *
 * It is a flat literal rather than a live import because pulling `webhooks-spec` into this app's TS
 * program drags the whole crypto package in under DOM libs (the Workers-vs-DOM lib clash). Same
 * trade-off, and the same test-only pin, as `provider-count.test.ts`.
 */
export interface ProviderEntry {
  /** The registry slug — the key into the brand-mark data in @webhook-co/ui. */
  readonly slug: string;
  /** The brand's display name, as the dashboard renders it. */
  readonly name: string;
}

export const PROVIDER_ENTRIES: readonly ProviderEntry[] = [
  { slug: "ably", name: "Ably" },
  { slug: "adyen", name: "Adyen" },
  { slug: "affirm", name: "Affirm" },
  { slug: "aftership", name: "AfterShip" },
  { slug: "airship", name: "Airship" },
  { slug: "airtable", name: "Airtable" },
  { slug: "airwallex", name: "Airwallex" },
  { slug: "aws_sns", name: "Amazon SNS" },
  { slug: "asana", name: "Asana" },
  { slug: "ashby", name: "Ashby" },
  { slug: "authorize_net", name: "Authorize.Net" },
  { slug: "autodesk_aps", name: "Autodesk Platform Services" },
  { slug: "bigcommerce", name: "BigCommerce" },
  { slug: "bitbucket", name: "Bitbucket" },
  { slug: "bolt", name: "Bolt" },
  { slug: "box", name: "Box" },
  { slug: "braintree", name: "Braintree" },
  { slug: "brevo", name: "Brevo" },
  { slug: "brex", name: "Brex" },
  { slug: "buildkite", name: "Buildkite" },
  { slug: "cal_com", name: "Cal.com" },
  { slug: "calendly", name: "Calendly" },
  { slug: "chargebee", name: "Chargebee" },
  { slug: "checkout_com", name: "Checkout.com" },
  { slug: "circleci", name: "CircleCI" },
  { slug: "clerk", name: "Clerk" },
  { slug: "clickup", name: "ClickUp" },
  { slug: "coinbase_commerce", name: "Coinbase Commerce" },
  { slug: "configcat", name: "ConfigCat" },
  { slug: "constant_contact", name: "Constant Contact" },
  { slug: "contentful", name: "Contentful" },
  { slug: "cronofy", name: "Cronofy" },
  { slug: "customer_io", name: "Customer.io" },
  { slug: "customerio", name: "Customer.io" },
  { slug: "datadog", name: "Datadog" },
  { slug: "deel", name: "Deel" },
  { slug: "discord", name: "Discord" },
  { slug: "docusign", name: "DocuSign" },
  { slug: "dropbox", name: "Dropbox" },
  { slug: "dub", name: "Dub" },
  { slug: "dwolla", name: "Dwolla" },
  { slug: "ebay", name: "eBay" },
  { slug: "etsy", name: "Etsy" },
  { slug: "fillout", name: "Fillout" },
  { slug: "finch", name: "Finch" },
  { slug: "framer", name: "Framer" },
  { slug: "front", name: "Front" },
  { slug: "github", name: "GitHub" },
  { slug: "gitlab", name: "GitLab" },
  { slug: "gocardless", name: "GoCardless" },
  { slug: "gemini", name: "Google Gemini" },
  { slug: "heroku", name: "Heroku" },
  { slug: "hubspot", name: "HubSpot" },
  { slug: "incident_io", name: "incident.io" },
  { slug: "increase", name: "Increase" },
  { slug: "intercom", name: "Intercom" },
  { slug: "atlassian_jira", name: "Jira" },
  { slug: "jira_connect", name: "Jira Connect" },
  { slug: "keygen", name: "Keygen" },
  { slug: "kinde", name: "Kinde" },
  { slug: "klaviyo", name: "Klaviyo" },
  { slug: "knock", name: "Knock" },
  { slug: "launchdarkly", name: "LaunchDarkly" },
  { slug: "lemon_squeezy", name: "Lemon Squeezy" },
  { slug: "linear", name: "Linear" },
  { slug: "linkedin", name: "LinkedIn" },
  { slug: "lob", name: "Lob" },
  { slug: "loops", name: "Loops" },
  { slug: "mailgun", name: "Mailgun" },
  { slug: "mandrill", name: "Mandrill" },
  { slug: "chargify", name: "Maxio" },
  { slug: "mercado_pago", name: "Mercado Pago" },
  { slug: "merge_dev", name: "Merge" },
  { slug: "messagebird", name: "MessageBird" },
  { slug: "meta", name: "Meta" },
  { slug: "microsoft_graph", name: "Microsoft Graph" },
  { slug: "ms_teams", name: "Microsoft Teams" },
  { slug: "mixpanel", name: "Mixpanel" },
  { slug: "modern_treasury", name: "Modern Treasury" },
  { slug: "monday", name: "monday.com" },
  { slug: "mongodb_atlas", name: "MongoDB Atlas" },
  { slug: "mux", name: "Mux" },
  { slug: "netlify", name: "Netlify" },
  { slug: "new_relic", name: "New Relic" },
  { slug: "notion", name: "Notion" },
  { slug: "npm", name: "npm" },
  { slug: "nylas", name: "Nylas" },
  { slug: "okta", name: "Okta" },
  { slug: "onfleet", name: "Onfleet" },
  { slug: "openai", name: "OpenAI" },
  { slug: "paddle", name: "Paddle" },
  { slug: "pagerduty", name: "PagerDuty" },
  { slug: "paypal", name: "PayPal" },
  { slug: "paystack", name: "Paystack" },
  { slug: "persona", name: "Persona" },
  { slug: "plaid", name: "Plaid" },
  { slug: "plivo", name: "Plivo" },
  { slug: "polar", name: "Polar" },
  { slug: "postmark", name: "Postmark" },
  { slug: "primer", name: "Primer" },
  { slug: "pusher", name: "Pusher" },
  { slug: "quickbooks", name: "QuickBooks" },
  { slug: "razorpay", name: "Razorpay" },
  { slug: "recurly", name: "Recurly" },
  { slug: "render", name: "Render" },
  { slug: "replicate", name: "Replicate" },
  { slug: "resend", name: "Resend" },
  { slug: "sanity", name: "Sanity" },
  { slug: "segment", name: "Segment" },
  { slug: "sendgrid", name: "SendGrid" },
  { slug: "sentry", name: "Sentry" },
  { slug: "shippo", name: "Shippo" },
  { slug: "shopify", name: "Shopify" },
  { slug: "sinch", name: "Sinch" },
  { slug: "slack", name: "Slack" },
  { slug: "sparkpost", name: "SparkPost" },
  { slug: "square", name: "Square" },
  { slug: "squarespace", name: "Squarespace" },
  { slug: "standard_webhooks", name: "Standard Webhooks" },
  { slug: "stripe", name: "Stripe" },
  { slug: "stytch", name: "Stytch" },
  { slug: "supabase", name: "Supabase" },
  { slug: "tally", name: "Tally" },
  { slug: "telegram", name: "Telegram" },
  { slug: "telnyx", name: "Telnyx" },
  { slug: "tiktok", name: "TikTok" },
  { slug: "trello", name: "Trello" },
  { slug: "twilio", name: "Twilio" },
  { slug: "twitch", name: "Twitch" },
  { slug: "typeform", name: "Typeform" },
  { slug: "vanta", name: "Vanta" },
  { slug: "vercel", name: "Vercel" },
  { slug: "vonage", name: "Vonage" },
  { slug: "webflow", name: "Webflow" },
  { slug: "wise", name: "Wise" },
  { slug: "woocommerce", name: "WooCommerce" },
  { slug: "workos", name: "WorkOS" },
  { slug: "x", name: "X" },
  { slug: "xero", name: "Xero" },
  { slug: "zapier", name: "Zapier" },
  { slug: "zendesk", name: "Zendesk" },
  { slug: "zoom", name: "Zoom" },
];
