/**
 * Every provider the verification registry can check: slug, display name, brand domain, and whether
 * @webhook-co/ui has an official vector mark for it.
 *
 * GENERATED — do not hand-edit. It is derived from `PROVIDERS` in `@webhook-co/webhooks-spec` (run
 * through the same `providerDisplayName` / `providerIconDomain` the dashboard uses), and
 * `provider-wall.test.tsx` re-derives all four fields from those packages and fails if they diverge.
 * Add the 142nd adapter and the test tells you to regenerate.
 *
 * It is a flat literal rather than a live import because pulling `webhooks-spec` into this app's TS
 * program drags the whole crypto package in under DOM libs (the Workers-vs-DOM lib clash). Same
 * trade-off, and the same test-only pin, as `provider-count.test.ts`.
 *
 * `scripts/fetch-provider-icons.mjs` reads this file to know which brands need a fetched icon
 * (`mark: false`) and from which domain.
 */
export interface ProviderEntry {
  /** The registry slug — the key into the brand-mark data in @webhook-co/ui. */
  readonly slug: string;
  /** The brand's display name, as the dashboard renders it. */
  readonly name: string;
  /** The brand's domain — the source for a fetched favicon when there is no vector mark. */
  readonly domain: string;
  /** True when @webhook-co/ui ships an official single-path vector mark (78 of the 141 do). */
  readonly mark: boolean;
}

export const PROVIDER_ENTRIES: readonly ProviderEntry[] = [
  { slug: "ably", name: "Ably", domain: "ably.com", mark: false },
  { slug: "adyen", name: "Adyen", domain: "", mark: true },
  { slug: "affirm", name: "Affirm", domain: "affirm.com", mark: false },
  { slug: "aftership", name: "AfterShip", domain: "", mark: true },
  { slug: "airship", name: "Airship", domain: "airship.com", mark: false },
  { slug: "airtable", name: "Airtable", domain: "", mark: true },
  { slug: "airwallex", name: "Airwallex", domain: "airwallex.com", mark: false },
  { slug: "aws_sns", name: "Amazon SNS", domain: "aws.amazon.com", mark: false },
  { slug: "asana", name: "Asana", domain: "", mark: true },
  { slug: "ashby", name: "Ashby", domain: "ashbyhq.com", mark: false },
  { slug: "authorize_net", name: "Authorize.Net", domain: "authorize.net", mark: false },
  { slug: "autodesk_aps", name: "Autodesk Platform Services", domain: "", mark: true },
  { slug: "bigcommerce", name: "BigCommerce", domain: "", mark: true },
  { slug: "bitbucket", name: "Bitbucket", domain: "", mark: true },
  { slug: "bolt", name: "Bolt", domain: "bolt.com", mark: false },
  { slug: "box", name: "Box", domain: "", mark: true },
  { slug: "braintree", name: "Braintree", domain: "", mark: true },
  { slug: "brevo", name: "Brevo", domain: "", mark: true },
  { slug: "brex", name: "Brex", domain: "", mark: true },
  { slug: "buildkite", name: "Buildkite", domain: "", mark: true },
  { slug: "cal_com", name: "Cal.com", domain: "", mark: true },
  { slug: "calendly", name: "Calendly", domain: "", mark: true },
  { slug: "chargebee", name: "Chargebee", domain: "chargebee.com", mark: false },
  { slug: "checkout_com", name: "Checkout.com", domain: "checkout.com", mark: false },
  { slug: "circleci", name: "CircleCI", domain: "", mark: true },
  { slug: "clerk", name: "Clerk", domain: "", mark: true },
  { slug: "clickup", name: "ClickUp", domain: "", mark: true },
  { slug: "coinbase_commerce", name: "Coinbase Commerce", domain: "", mark: true },
  { slug: "configcat", name: "ConfigCat", domain: "configcat.com", mark: false },
  {
    slug: "constant_contact",
    name: "Constant Contact",
    domain: "constantcontact.com",
    mark: false,
  },
  { slug: "contentful", name: "Contentful", domain: "", mark: true },
  { slug: "cronofy", name: "Cronofy", domain: "cronofy.com", mark: false },
  { slug: "customer_io", name: "Customer.io", domain: "customer.io", mark: false },
  { slug: "datadog", name: "Datadog", domain: "", mark: true },
  { slug: "deel", name: "Deel", domain: "deel.com", mark: false },
  { slug: "discord", name: "Discord", domain: "", mark: true },
  { slug: "docusign", name: "DocuSign", domain: "docusign.com", mark: false },
  { slug: "dropbox", name: "Dropbox", domain: "", mark: true },
  { slug: "dub", name: "Dub", domain: "dub.co", mark: false },
  { slug: "dwolla", name: "Dwolla", domain: "dwolla.com", mark: false },
  { slug: "ebay", name: "eBay", domain: "", mark: true },
  { slug: "etsy", name: "Etsy", domain: "", mark: true },
  { slug: "fillout", name: "Fillout", domain: "", mark: true },
  { slug: "finch", name: "Finch", domain: "tryfinch.com", mark: false },
  { slug: "framer", name: "Framer", domain: "", mark: true },
  { slug: "front", name: "Front", domain: "front.com", mark: false },
  { slug: "github", name: "GitHub", domain: "", mark: true },
  { slug: "gitlab", name: "GitLab", domain: "", mark: true },
  { slug: "gocardless", name: "GoCardless", domain: "gocardless.com", mark: false },
  { slug: "gemini", name: "Google Gemini", domain: "", mark: true },
  { slug: "heroku", name: "Heroku", domain: "heroku.com", mark: false },
  { slug: "hubspot", name: "HubSpot", domain: "", mark: true },
  { slug: "incident_io", name: "incident.io", domain: "incident.io", mark: false },
  { slug: "increase", name: "Increase", domain: "increase.com", mark: false },
  { slug: "intercom", name: "Intercom", domain: "", mark: true },
  { slug: "atlassian_jira", name: "Jira", domain: "", mark: true },
  { slug: "jira_connect", name: "Jira Connect", domain: "", mark: true },
  { slug: "keygen", name: "Keygen", domain: "keygen.sh", mark: false },
  { slug: "kinde", name: "Kinde", domain: "kinde.com", mark: false },
  { slug: "klaviyo", name: "Klaviyo", domain: "klaviyo.com", mark: false },
  { slug: "knock", name: "Knock", domain: "knock.app", mark: false },
  { slug: "launchdarkly", name: "LaunchDarkly", domain: "launchdarkly.com", mark: false },
  { slug: "lemon_squeezy", name: "Lemon Squeezy", domain: "", mark: true },
  { slug: "linear", name: "Linear", domain: "", mark: true },
  { slug: "linkedin", name: "LinkedIn", domain: "linkedin.com", mark: false },
  { slug: "lob", name: "Lob", domain: "lob.com", mark: false },
  { slug: "loops", name: "Loops", domain: "", mark: true },
  { slug: "mailgun", name: "Mailgun", domain: "", mark: true },
  { slug: "mandrill", name: "Mandrill", domain: "mailchimp.com", mark: false },
  { slug: "chargify", name: "Maxio", domain: "maxio.com", mark: false },
  { slug: "mercado_pago", name: "Mercado Pago", domain: "", mark: true },
  { slug: "merge_dev", name: "Merge", domain: "merge.dev", mark: false },
  { slug: "messagebird", name: "MessageBird", domain: "messagebird.com", mark: false },
  { slug: "meta", name: "Meta", domain: "", mark: true },
  { slug: "microsoft_graph", name: "Microsoft Graph", domain: "microsoft.com", mark: false },
  { slug: "ms_teams", name: "Microsoft Teams", domain: "microsoft.com", mark: false },
  { slug: "mixpanel", name: "Mixpanel", domain: "", mark: true },
  { slug: "modern_treasury", name: "Modern Treasury", domain: "moderntreasury.com", mark: false },
  { slug: "monday", name: "monday.com", domain: "monday.com", mark: false },
  { slug: "mongodb_atlas", name: "MongoDB Atlas", domain: "", mark: true },
  { slug: "mux", name: "Mux", domain: "mux.com", mark: false },
  { slug: "netlify", name: "Netlify", domain: "", mark: true },
  { slug: "new_relic", name: "New Relic", domain: "", mark: true },
  { slug: "notion", name: "Notion", domain: "", mark: true },
  { slug: "npm", name: "npm", domain: "", mark: true },
  { slug: "nylas", name: "Nylas", domain: "nylas.com", mark: false },
  { slug: "okta", name: "Okta", domain: "", mark: true },
  { slug: "onfleet", name: "Onfleet", domain: "onfleet.com", mark: false },
  { slug: "openai", name: "OpenAI", domain: "openai.com", mark: false },
  { slug: "paddle", name: "Paddle", domain: "", mark: true },
  { slug: "pagerduty", name: "PagerDuty", domain: "", mark: true },
  { slug: "paypal", name: "PayPal", domain: "", mark: true },
  { slug: "paystack", name: "Paystack", domain: "paystack.com", mark: false },
  { slug: "persona", name: "Persona", domain: "withpersona.com", mark: false },
  { slug: "plaid", name: "Plaid", domain: "plaid.com", mark: false },
  { slug: "plivo", name: "Plivo", domain: "plivo.com", mark: false },
  { slug: "polar", name: "Polar", domain: "polar.sh", mark: false },
  { slug: "postmark", name: "Postmark", domain: "postmarkapp.com", mark: false },
  { slug: "primer", name: "Primer", domain: "primer.io", mark: false },
  { slug: "pusher", name: "Pusher", domain: "", mark: true },
  { slug: "quickbooks", name: "QuickBooks", domain: "", mark: true },
  { slug: "razorpay", name: "Razorpay", domain: "", mark: true },
  { slug: "recurly", name: "Recurly", domain: "recurly.com", mark: false },
  { slug: "render", name: "Render", domain: "", mark: true },
  { slug: "replicate", name: "Replicate", domain: "", mark: true },
  { slug: "resend", name: "Resend", domain: "", mark: true },
  { slug: "sanity", name: "Sanity", domain: "", mark: true },
  { slug: "segment", name: "Segment", domain: "segment.com", mark: false },
  { slug: "sendgrid", name: "SendGrid", domain: "sendgrid.com", mark: false },
  { slug: "sentry", name: "Sentry", domain: "", mark: true },
  { slug: "shippo", name: "Shippo", domain: "goshippo.com", mark: false },
  { slug: "shopify", name: "Shopify", domain: "", mark: true },
  { slug: "sinch", name: "Sinch", domain: "sinch.com", mark: false },
  { slug: "slack", name: "Slack", domain: "slack.com", mark: false },
  { slug: "sparkpost", name: "SparkPost", domain: "", mark: true },
  { slug: "square", name: "Square", domain: "", mark: true },
  { slug: "squarespace", name: "Squarespace", domain: "", mark: true },
  {
    slug: "standard_webhooks",
    name: "Standard Webhooks",
    domain: "standardwebhooks.com",
    mark: false,
  },
  { slug: "stripe", name: "Stripe", domain: "", mark: true },
  { slug: "stytch", name: "Stytch", domain: "stytch.com", mark: false },
  { slug: "supabase", name: "Supabase", domain: "", mark: true },
  { slug: "tally", name: "Tally", domain: "tally.so", mark: false },
  { slug: "telegram", name: "Telegram", domain: "", mark: true },
  { slug: "telnyx", name: "Telnyx", domain: "telnyx.com", mark: false },
  { slug: "tiktok", name: "TikTok", domain: "", mark: true },
  { slug: "trello", name: "Trello", domain: "", mark: true },
  { slug: "twilio", name: "Twilio", domain: "twilio.com", mark: false },
  { slug: "twitch", name: "Twitch", domain: "", mark: true },
  { slug: "typeform", name: "Typeform", domain: "", mark: true },
  { slug: "vanta", name: "Vanta", domain: "vanta.com", mark: false },
  { slug: "vercel", name: "Vercel", domain: "", mark: true },
  { slug: "vonage", name: "Vonage", domain: "", mark: true },
  { slug: "webflow", name: "Webflow", domain: "", mark: true },
  { slug: "wise", name: "Wise", domain: "", mark: true },
  { slug: "woocommerce", name: "WooCommerce", domain: "", mark: true },
  { slug: "workos", name: "WorkOS", domain: "workos.com", mark: false },
  { slug: "x", name: "X", domain: "", mark: true },
  { slug: "xero", name: "Xero", domain: "", mark: true },
  { slug: "zapier", name: "Zapier", domain: "", mark: true },
  { slug: "zendesk", name: "Zendesk", domain: "", mark: true },
  { slug: "zoom", name: "Zoom", domain: "", mark: true },
];
