/**
 * Every provider the verification registry can check, by display name.
 *
 * This is DATA, not a claim someone typed: it is generated from `PROVIDERS` in
 * `@webhook-co/webhooks-spec` (run through the same `providerDisplayName` the dashboard uses), and
 * `provider-wall.test.tsx` re-derives it from that registry and fails if the two ever diverge. Add
 * the 143rd adapter and the test tells you to regenerate this file.
 *
 * It is a flat literal rather than a live import because pulling `webhooks-spec` into this app's TS
 * program drags the whole crypto package in under DOM libs (the Workers-vs-DOM lib clash) and would
 * cost bundle bytes we don't have — the site is a static export under a hard 600 KB budget. Same
 * trade-off, and the same test-only pin, as `provider-count.test.ts`.
 */
export const PROVIDER_NAMES: readonly string[] = [
  "Ably",
  "Adyen",
  "Affirm",
  "AfterShip",
  "Airship",
  "Airtable",
  "Airwallex",
  "Amazon SNS",
  "Asana",
  "Ashby",
  "Authorize.Net",
  "Autodesk Platform Services",
  "BigCommerce",
  "Bitbucket",
  "Bolt",
  "Box",
  "Braintree",
  "Brevo",
  "Brex",
  "Buildkite",
  "Cal.com",
  "Calendly",
  "Chargebee",
  "Checkout.com",
  "CircleCI",
  "Clerk",
  "ClickUp",
  "Coinbase Commerce",
  "ConfigCat",
  "Constant Contact",
  "Contentful",
  "Cronofy",
  "Customer.io",
  "Customer.io",
  "Datadog",
  "Deel",
  "Discord",
  "DocuSign",
  "Dropbox",
  "Dub",
  "Dwolla",
  "eBay",
  "Etsy",
  "Fillout",
  "Finch",
  "Framer",
  "Front",
  "GitHub",
  "GitLab",
  "GoCardless",
  "Google Gemini",
  "Heroku",
  "HubSpot",
  "incident.io",
  "Increase",
  "Intercom",
  "Jira",
  "Jira Connect",
  "Keygen",
  "Kinde",
  "Klaviyo",
  "Knock",
  "LaunchDarkly",
  "Lemon Squeezy",
  "Linear",
  "LinkedIn",
  "Lob",
  "Loops",
  "Mailgun",
  "Mandrill",
  "Maxio",
  "Mercado Pago",
  "Merge",
  "MessageBird",
  "Meta",
  "Microsoft Graph",
  "Microsoft Teams",
  "Mixpanel",
  "Modern Treasury",
  "monday.com",
  "MongoDB Atlas",
  "Mux",
  "Netlify",
  "New Relic",
  "Notion",
  "npm",
  "Nylas",
  "Okta",
  "Onfleet",
  "OpenAI",
  "Paddle",
  "PagerDuty",
  "PayPal",
  "Paystack",
  "Persona",
  "Plaid",
  "Plivo",
  "Polar",
  "Postmark",
  "Primer",
  "Pusher",
  "QuickBooks",
  "Razorpay",
  "Recurly",
  "Render",
  "Replicate",
  "Resend",
  "Sanity",
  "Segment",
  "SendGrid",
  "Sentry",
  "Shippo",
  "Shopify",
  "Sinch",
  "Slack",
  "SparkPost",
  "Square",
  "Squarespace",
  "Standard Webhooks",
  "Stripe",
  "Stytch",
  "Supabase",
  "Tally",
  "Telegram",
  "Telnyx",
  "TikTok",
  "Trello",
  "Twilio",
  "Twitch",
  "Typeform",
  "Vanta",
  "Vercel",
  "Vonage",
  "Webflow",
  "Wise",
  "WooCommerce",
  "WorkOS",
  "X",
  "Xero",
  "Zapier",
  "Zendesk",
  "Zoom",
];
