#!/usr/bin/env node
// Generate the local `.dev.vars` every Worker needs, from scripts/dev-secrets-manifest.mjs.
//
//   pnpm dev:secrets            write/fill apps/<app>/.dev.vars
//   pnpm dev:secrets --check    verify the committed dev.vars.example files match the manifest
//   pnpm dev:secrets --examples regenerate the committed dev.vars.example files
//
// Design rules, each earned from something the audit found:
//
//  * Shared secrets are generated ONCE and written identically to every app that reads them. web
//    minted listen tickets with a hardcoded fallback because LISTEN_TICKET_KEY was only in engine's
//    file; the symptom was a dead WebSocket, not a config error.
//  * Existing values are NEVER overwritten. A tool that eats your hand-pasted Stripe test key on
//    every run is a tool people stop running.
//  * `external` secrets are written EMPTY. Nothing here should look like a plausible credential —
//    these files get pasted into issues.
//  * Nothing is a committed constant. A default pepper shipped in git is a shared secret wearing a
//    different hat.

import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { APP_NAMES, GENERATED_BYTES, specsFor } from "./dev-secrets-manifest.mjs";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Parse `KEY=value` lines. Comments and blanks ignored; only the FIRST `=` splits. */
export function parseDevVars(text) {
  /** @type {Record<string,string>} */
  const out = {};
  for (const raw of String(text).split("\n")) {
    const lineText = raw.trim();
    if (!lineText || lineText.startsWith("#")) continue;
    const eq = lineText.indexOf("=");
    if (eq === -1) continue;
    // Split on the FIRST `=` only: base64 secrets are padded with `=` and would otherwise truncate.
    out[lineText.slice(0, eq)] = lineText.slice(eq + 1);
  }
  return out;
}

/** Render a `.dev.vars` for an app from a name→value map. */
export function renderDevVars(app, values) {
  const specs = specsFor(app);
  const lines = [
    `# apps/${app}/.dev.vars — generated by \`pnpm dev:secrets\`. GITIGNORED; never commit it.`,
    `# Values are yours alone. Re-running fills only what is missing and never overwrites.`,
    `# Key names and their meaning live in scripts/dev-secrets-manifest.mjs.`,
    ``,
  ];
  for (const spec of specs) {
    lines.push(`# ${spec.scope.toUpperCase()}: ${spec.note}`);
    lines.push(`${spec.name}=${values[spec.name] ?? ""}`);
    lines.push(``);
  }
  return lines.join("\n").replace(/\n+$/, "\n");
}

/** Render the COMMITTED example: every key name, notes, literals filled, secrets blank. */
export function renderExample(app) {
  const values = {};
  for (const spec of specsFor(app)) {
    // Only non-secret literals carry a value here. This file is committed.
    values[spec.name] = spec.scope === "local" ? spec.value : "";
  }
  return (
    renderDevVars(app, values)
      .replace(
        `# apps/${app}/.dev.vars — generated by \`pnpm dev:secrets\`. GITIGNORED; never commit it.`,
        `# apps/${app}/dev.vars.example — COMMITTED reference, regenerated by \`pnpm dev:secrets --examples\`.\n# Run \`pnpm dev:secrets\` to write the real apps/${app}/.dev.vars with generated values.\n# Never paste a secret into this file: it is committed, and this repo is public.`,
      )
      // Only true of the generated .dev.vars, not of this committed reference.
      .replace(
        `# Values are yours alone. Re-running fills only what is missing and never overwrites.\n`,
        "",
      )
  );
}

/**
 * Write/fill `.dev.vars` for every app.
 * @param {{root?: string}} [opts]
 * @returns {{app: string, path: string, added: string[]}[]}
 */
export function generateDevVars(opts = {}) {
  const root = opts.root ?? REPO_ROOT;

  // Generate each shared secret once, then reuse it for every app that declares it. If a value
  // already exists on disk anywhere, adopt THAT one — otherwise a partially-written tree would get a
  // fresh value for one app and keep the old one for another, which is the mismatch we are fixing.
  /** @type {Record<string,string>} */
  const sharedValues = {};
  const existing = new Map();
  for (const app of APP_NAMES) {
    const p = join(root, "apps", app, ".dev.vars");
    existing.set(app, existsSync(p) ? parseDevVars(readFileSync(p, "utf8")) : {});
  }
  for (const app of APP_NAMES) {
    for (const spec of specsFor(app)) {
      if (!spec.shared) continue;
      const found = existing.get(app)[spec.name];
      if (found && !sharedValues[spec.name]) sharedValues[spec.name] = found;
    }
  }

  const results = [];
  for (const app of APP_NAMES) {
    const dir = join(root, "apps", app);
    mkdirSync(dir, { recursive: true });
    const path = join(dir, ".dev.vars");
    const prior = existing.get(app);
    /** @type {Record<string,string>} */
    const values = {};
    const added = [];

    for (const spec of specsFor(app)) {
      const already = prior[spec.name];
      if (already !== undefined && already !== "") {
        values[spec.name] = already; // never overwrite
        continue;
      }
      if (spec.scope === "generated") {
        if (spec.shared) {
          sharedValues[spec.name] ??= randomBytes(GENERATED_BYTES).toString("base64");
          values[spec.name] = sharedValues[spec.name];
        } else {
          values[spec.name] = randomBytes(GENERATED_BYTES).toString("base64");
        }
        added.push(spec.name);
      } else if (spec.scope === "local") {
        values[spec.name] = spec.value ?? "";
        added.push(spec.name);
      } else {
        values[spec.name] = ""; // external — the developer supplies it, or the feature stays dark
      }
    }

    const next = renderDevVars(app, values);
    if (!existsSync(path) || readFileSync(path, "utf8") !== next) writeFileSync(path, next);
    results.push({ app, path, added });
  }
  return results;
}

/** Rewrite the committed examples. */
export function writeExamples(root = REPO_ROOT) {
  const written = [];
  for (const app of APP_NAMES) {
    const p = join(root, "apps", app, "dev.vars.example");
    writeFileSync(p, renderExample(app));
    written.push(p);
  }
  return written;
}

/** Verify the committed examples match the manifest. Returns a list of drifted paths. */
export function checkExamples(root = REPO_ROOT) {
  const drifted = [];
  for (const app of APP_NAMES) {
    const p = join(root, "apps", app, "dev.vars.example");
    const want = renderExample(app);
    const have = existsSync(p) ? readFileSync(p, "utf8") : null;
    if (have !== want) drifted.push(`apps/${app}/dev.vars.example`);
  }
  return drifted;
}

// ── CLI ──────────────────────────────────────────────────────────────────────────────────────────
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const arg = process.argv[2] ?? "";
  if (arg === "--check") {
    const drifted = checkExamples();
    if (drifted.length) {
      console.error(
        `❌ committed examples are out of date with scripts/dev-secrets-manifest.mjs:\n` +
          drifted.map((d) => `   ${d}`).join("\n") +
          `\n\n   pnpm dev:secrets --examples`,
      );
      process.exit(1);
    }
    console.log("✅ dev.vars.example files match the manifest");
  } else if (arg === "--examples") {
    for (const p of writeExamples()) console.log(`wrote ${p.replace(`${REPO_ROOT}/`, "")}`);
  } else {
    const results = generateDevVars();
    console.log("✅ local secrets ready — generated values, no shared credentials\n");
    for (const { app, added } of results) {
      console.log(
        added.length
          ? `   apps/${app}/.dev.vars  +${added.length} (${added.join(", ")})`
          : `   apps/${app}/.dev.vars  up to date`,
      );
    }
    console.log(
      `\n   Blank keys need a real third-party credential and are OPTIONAL — the feature stays` +
        `\n   dark without them. See apps/<app>/dev.vars.example for what each one unlocks.`,
    );
  }
}
