#!/usr/bin/env node
// Generate the local `.dev.vars` every Worker needs, from scripts/dev-secrets-manifest.mjs.
//
//   pnpm dev:secrets            write/fill apps/<app>/.dev.vars
//   pnpm dev:secrets --check    verify the committed dev.vars.example files match the manifest
//   pnpm dev:secrets --examples regenerate the committed dev.vars.example files
//
// Design rules, each earned from something the audit found:
//
//  * Shared secrets are generated ONCE and written identically to every app that reads them. web
//    minted listen tickets with a hardcoded fallback because LISTEN_TICKET_KEY was only in engine's
//    file; the symptom was a dead WebSocket, not a config error.
//  * Existing values are NEVER overwritten. A tool that eats your hand-pasted Stripe test key on
//    every run is a tool people stop running.
//  * `external` secrets are written EMPTY. Nothing here should look like a plausible credential —
//    these files get pasted into issues.
//  * Nothing is a committed constant. A default pepper shipped in git is a shared secret wearing a
//    different hat.

import { randomBytes } from "node:crypto";
import { chmodSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { APP_NAMES, GENERATED_BYTES, sharedNames, specsFor } from "./dev-secrets-manifest.mjs";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Read a file, or null when it does not exist.
 *
 * Deliberately try/catch rather than `existsSync(p) ? readFileSync(p) : null`: the check-then-use
 * pair is a TOCTOU race (CodeQL js/file-system-race) and there is no reason to write one when the
 * single-call form is both simpler and correct.
 */
function readIfPresent(p) {
  try {
    return readFileSync(p, "utf8");
  } catch (err) {
    if (err.code === "ENOENT") return null;
    throw err;
  }
}

/** Parse `KEY=value` lines. Comments and blanks ignored; only the FIRST `=` splits. */
export function parseDevVars(text) {
  /** @type {Record<string,string>} */
  const out = {};
  for (const raw of String(text).split("\n")) {
    const lineText = raw.trim();
    if (!lineText || lineText.startsWith("#")) continue;
    const eq = lineText.indexOf("=");
    if (eq === -1) continue;
    // Split on the FIRST `=` only: base64 secrets are padded with `=` and would otherwise truncate.
    const key = lineText.slice(0, eq).trim();
    if (!key) continue;
    let value = lineText.slice(eq + 1).trim();
    // Match what wrangler actually does — it reads .dev.vars with dotenv, which trims around `=` and
    // strips matching surrounding quotes. If we disagree, a legal `KEY = value` reads as ABSENT here
    // and the rewrite blanks it, or mints a NEW shared secret while wrangler keeps using the old one.
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

/** Render a `.dev.vars` for an app from a name→value map. */
export function renderDevVars(app, values, opts = {}) {
  const specs = specsFor(app);
  // The header is a PARAMETER, not post-hoc string surgery. Rewriting it with .replace() meant a
  // wording change in one place silently produced a COMMITTED example reading "GITIGNORED; never
  // commit it" — a no-op .replace() is invisible.
  const lines = [
    ...(opts.header ?? [
      `# apps/${app}/.dev.vars — generated by \`pnpm dev:secrets\`. GITIGNORED; never commit it.`,
      `# Values are yours alone. Re-running fills only what is missing and never overwrites.`,
    ]),
    `# Key names and their meaning live in scripts/dev-secrets-manifest.mjs.`,
    ``,
  ];
  for (const spec of specs) {
    lines.push(`# ${spec.scope.toUpperCase()}: ${spec.note}`);
    lines.push(`${spec.name}=${values[spec.name] ?? ""}`);
    lines.push(``);
  }
  // Anything on disk the manifest does not know about is PRESERVED. Rewriting only the manifest's
  // keys silently deleted them — including AUTH_BASE_URL, which apps/auth/src/runtime/env.ts:37 tells
  // you to set in .dev.vars "so the handoff redirects to localhost, not prod". Deleting it points the
  // local auth handoff at PRODUCTION.
  const known = new Set(specs.map((s2) => s2.name));
  const extra = Object.keys(values).filter((k) => !known.has(k));
  if (extra.length) {
    lines.push(`# --- not in scripts/dev-secrets-manifest.mjs; preserved as you left them ---`);
    for (const k of extra.sort()) lines.push(`${k}=${values[k]}`);
    lines.push(``);
  }
  return lines.join("\n").replace(/\n+$/, "\n");
}

/** Render the COMMITTED example: every key name, notes, literals filled, secrets blank. */
export function renderExample(app) {
  const values = {};
  for (const spec of specsFor(app)) {
    // Only non-secret literals carry a value here. This file is committed.
    values[spec.name] = spec.scope === "local" ? spec.value : "";
  }
  return renderDevVars(app, values, {
    header: [
      `# apps/${app}/dev.vars.example — COMMITTED reference, regenerated by \`pnpm dev:secrets --examples\`.`,
      `# Run \`pnpm dev:secrets\` to write the real apps/${app}/.dev.vars with generated values.`,
      `# Never paste a secret into this file: it is committed, and this repo is public.`,
    ],
  });
}

/**
 * Write/fill `.dev.vars` for every app.
 * @param {{root?: string}} [opts]
 * @returns {{app: string, path: string, added: string[]}[]}
 */
export function generateDevVars(opts = {}) {
  const root = opts.root ?? REPO_ROOT;

  /** @type {Record<string,string>} */
  const sharedValues = {};
  const existing = new Map();
  for (const app of APP_NAMES) {
    const p = join(root, "apps", app, ".dev.vars");
    const text = readIfPresent(p);
    existing.set(app, text === null ? {} : parseDevVars(text));
  }

  // Collect EVERY on-disk value for each shared name, then refuse if they disagree.
  //
  // Adopting the first app's value and letting "never overwrite" win for the rest left a pre-existing
  // mismatch in place FOREVER while printing success — a no-op on precisely the machines that have the
  // bug, and it would even spread one arbitrary value to the empty apps, turning a 1-vs-1 split into a
  // 4-vs-1 one. scripts/dev-db-config.mjs already set the precedent: disagreement is fatal, because a
  // half-provisioned tree is worse than none.
  for (const name of sharedNames()) {
    /** @type {Map<string,string>} */
    const byApp = new Map();
    for (const app of APP_NAMES) {
      if (!specsFor(app).some((s2) => s2.name === name)) continue;
      const v = existing.get(app)[name];
      if (v) byApp.set(app, v);
    }
    const distinct = new Set(byApp.values());
    if (distinct.size > 1 && !opts.converge) {
      // App names and value LENGTHS only — never any part of the value itself. This message goes to a
      // terminal and gets pasted into issues, and a suffix is not needed to act on it.
      const detail = [...byApp.entries()]
        .map(([a, v]) => `   apps/${a}: ${v.length} chars`)
        .join("\n");
      throw new Error(
        `${name} must be identical across apps, but they disagree:\n${detail}\n\n` +
          `   This is the mismatch that presents as a dead dashboard WebSocket with no config error.\n` +
          `   Re-run with --converge to overwrite them onto one value (safe locally: these are\n` +
          `   generated dev secrets, not credentials anyone else holds).`,
      );
    }
    if (distinct.size >= 1) sharedValues[name] = [...distinct][0];
  }

  const results = [];
  for (const app of APP_NAMES) {
    const dir = join(root, "apps", app);
    mkdirSync(dir, { recursive: true });
    const path = join(dir, ".dev.vars");
    const prior = existing.get(app);
    /** @type {Record<string,string>} */
    const values = {};
    const added = [];

    for (const spec of specsFor(app)) {
      const already = prior[spec.name];
      // A shared secret is the one case where an existing value does NOT automatically win: converging
      // is the whole point. Everything else is preserved as the developer left it.
      if (already !== undefined && already !== "" && !(spec.shared && opts.converge)) {
        values[spec.name] = already;
        continue;
      }
      if (spec.scope === "generated") {
        if (spec.shared) {
          sharedValues[spec.name] ??= randomBytes(GENERATED_BYTES).toString("base64");
          values[spec.name] = sharedValues[spec.name];
        } else {
          values[spec.name] = randomBytes(GENERATED_BYTES).toString("base64");
        }
        added.push(spec.name);
      } else if (spec.scope === "local") {
        values[spec.name] = spec.value ?? "";
        added.push(spec.name);
      } else {
        values[spec.name] = ""; // external — supplied by the developer, or the feature stays dark
      }
    }

    // Carry over anything the manifest does not declare, so the rewrite is never lossy.
    for (const [k, v] of Object.entries(prior)) if (!(k in values)) values[k] = v;

    const next = renderDevVars(app, values);
    if (readIfPresent(path) !== next) {
      // 0600: these hold the credential pepper and the session-signing key.
      writeFileSync(path, next, { mode: 0o600 });
    }
    chmodSync(path, 0o600); // mode is not applied when overwriting an existing file
    results.push({ app, path, added });
  }
  return results;
}

/** Rewrite the committed examples. */
export function writeExamples(root = REPO_ROOT) {
  const written = [];
  for (const app of APP_NAMES) {
    const p = join(root, "apps", app, "dev.vars.example");
    writeFileSync(p, renderExample(app));
    written.push(p);
  }
  return written;
}

/** Verify the committed examples match the manifest. Returns a list of drifted paths. */
export function checkExamples(root = REPO_ROOT) {
  // Zero-input floor: iterating an empty APP_NAMES would return [] and pass with a green tick.
  if (APP_NAMES.length < 5) {
    throw new Error(
      `dev-secrets: expected at least 5 apps in the manifest, got ${APP_NAMES.length}`,
    );
  }
  const drifted = [];
  for (const app of APP_NAMES) {
    const p = join(root, "apps", app, "dev.vars.example");
    const want = renderExample(app);
    const have = readIfPresent(p);
    if (have !== want) drifted.push(`apps/${app}/dev.vars.example`);
  }
  return drifted;
}

/**
 * Committed dev.vars.example files with no manifest entry. Discovered from disk, not listed — remove
 * an app from APPS and its example would otherwise linger with stale key names, guard green.
 */
export function orphanExamples(root = REPO_ROOT) {
  const appsDir = join(root, "apps");
  const known = new Set(APP_NAMES);
  return readdirSync(appsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !known.has(e.name))
    .filter((e) => readIfPresent(join(appsDir, e.name, "dev.vars.example")) !== null)
    .map((e) => `apps/${e.name}/dev.vars.example`);
}

// ── CLI ──────────────────────────────────────────────────────────────────────────────────────────
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const arg = process.argv[2] ?? "";
  if (arg === "--check") {
    const orphans = orphanExamples();
    if (orphans.length) {
      console.error(
        `❌ committed example(s) with no manifest entry:\n` +
          orphans.map((o) => `   ${o}`).join("\n"),
      );
      process.exit(1);
    }
    const drifted = checkExamples();
    if (drifted.length) {
      console.error(
        `❌ committed examples are out of date with scripts/dev-secrets-manifest.mjs:\n` +
          drifted.map((d) => `   ${d}`).join("\n") +
          `\n\n   pnpm dev:secrets --examples`,
      );
      process.exit(1);
    }
    console.log("✅ dev.vars.example files match the manifest");
  } else if (arg === "--examples") {
    for (const p of writeExamples()) console.log(`wrote ${p.replace(`${REPO_ROOT}/`, "")}`);
  } else {
    const converge = arg === "--converge" || process.argv.includes("--converge");
    let results;
    try {
      results = generateDevVars({ converge });
    } catch (err) {
      console.error(`❌ ${err.message}`);
      process.exit(1);
    }
    console.log("✅ local secrets ready — generated values, no shared credentials\n");
    for (const { app, added } of results) {
      console.log(
        added.length
          ? `   apps/${app}/.dev.vars  +${added.length} (${added.join(", ")})`
          : `   apps/${app}/.dev.vars  up to date`,
      );
    }
    console.log(
      `\n   Blank keys need a real third-party credential and are OPTIONAL — the feature stays` +
        `\n   dark without them. See apps/<app>/dev.vars.example for what each one unlocks.`,
    );
  }
}
