import assert from "node:assert/strict";
import { test } from "node:test";

import { CALLING_APPS, devConfigFor } from "./gen-wrangler-dev.mjs";
import { extractServices, SERVICE_BINDINGS } from "./wrangler-services.mjs";

// The dev overlay exists because the service bindings are deliberately NOT committed: Cloudflare rejects
// an upload naming a Worker that is not live yet, so committing them would block a cold deploy. The
// generated, gitignored config gives `wrangler dev` the bindings without changing what ships.

const MINIMAL = '{\n  "name": "webhook-api",\n  "main": "src/index.ts"\n}\n';

test("the calling apps come from the shared table, never a second list", () => {
  assert.deepEqual([...CALLING_APPS].sort(), Object.keys(SERVICE_BINDINGS).sort());
  assert.ok(CALLING_APPS.length >= 3, `expected ≥3 calling apps, got ${CALLING_APPS.length}`);
});

test("a config with no committed services gets the full injected set", () => {
  const out = devConfigFor("api", MINIMAL);
  const { entries } = extractServices(out);
  assert.equal(entries.length, SERVICE_BINDINGS.api.length);
  assert.deepEqual(
    entries.map((e) => e.binding).sort(),
    SERVICE_BINDINGS.api.map((e) => e.binding).sort(),
  );
});

test("the generated config declares `services` exactly ONCE", () => {
  // The prod generator shipped this bug: injecting on top of a committed block left the key twice, and
  // which one wins is parser-dependent (wrangler takes the first, JSON.parse the last).
  const committed =
    '{\n  "name": "webhook-mcp",\n  "services": [\n    { "binding": "AUTH_ISSUER", "service": "webhook-auth", "entrypoint": "IssuerIntrospect" }\n  ]\n}\n';
  const out = devConfigFor("mcp", committed);
  assert.equal((out.match(/"services"\s*:/g) ?? []).length, 1);
});

test("a binding committed but absent from the table is KEPT, not dropped", () => {
  const committed =
    '{\n  "name": "webhook-api",\n  "services": [\n    { "binding": "LEGACY_ONLY", "service": "webhook-engine", "entrypoint": "Legacy" }\n  ]\n}\n';
  const { entries } = extractServices(devConfigFor("api", committed));
  assert.ok(
    entries.some((e) => e.binding === "LEGACY_ONLY"),
    "merging dropped a binding the committed config declared",
  );
  assert.equal(entries.length, SERVICE_BINDINGS.api.length + 1);
});

test("the rest of the committed config survives verbatim", () => {
  const out = devConfigFor("api", MINIMAL);
  assert.ok(out.includes('"name": "webhook-api"'), "the worker name was lost");
  assert.ok(out.includes('"main": "src/index.ts"'), "the entry module was lost");
});

test("the output is marked generated, so nobody edits it by hand", () => {
  assert.match(devConfigFor("api", MINIMAL), /GENERATED by scripts\/gen-wrangler-dev\.mjs/);
});

// Anti-vacuity: if devConfigFor returned its input unchanged, every "contains" assertion above would
// still pass on a committed config that happened to carry the bindings already.
test("an app that calls nobody produces no config at all", () => {
  assert.equal(devConfigFor("engine", MINIMAL), null);
});
