// Assemble the full recipe set for every provider in the registry vocabulary. Precedence matches
// the engine's `getAdapterForScheme` (registry.ts): a hand-written BESPOKE adapter wins over the
// config-derived one for the same slug (e.g. Twilio's real form+JSON adapter, not its form-only
// config row). Every provider MUST resolve to exactly one recipe source, or generation fails —
// so a newly-added provider can never silently ship without a recipe.

import { PROVIDERS, PROVIDER_CONFIGS } from "@webhook-co/webhooks-spec";
import { buildRecipe } from "./build-recipe";
import { BESPOKE_RECIPES } from "./bespoke-recipes";
import type { RecipeDescriptor } from "./types";

export function buildAllRecipes(): RecipeDescriptor[] {
  const out: RecipeDescriptor[] = [];
  for (const slug of PROVIDERS) {
    const bespoke = BESPOKE_RECIPES[slug];
    if (bespoke) {
      if (bespoke.slug !== slug) {
        throw new Error(
          `BESPOKE_RECIPES["${slug}"].slug is "${bespoke.slug}" — must match its key`,
        );
      }
      out.push(bespoke);
      continue;
    }
    const config = PROVIDER_CONFIGS[slug as keyof typeof PROVIDER_CONFIGS];
    if (config) {
      out.push(buildRecipe(config));
      continue;
    }
    throw new Error(
      `provider "${slug}" has neither a config row nor a bespoke recipe — add one to BESPOKE_RECIPES`,
    );
  }
  return out;
}

/** Deterministic golden module content (byte-compared in CI to catch hand-edits + drift). */
export function renderGolden(recipes: readonly RecipeDescriptor[]): string {
  const header =
    "// GENERATED by @webhook-co/webhooks-recipes — DO NOT EDIT BY HAND.\n" +
    "// Run `pnpm --filter @webhook-co/webhooks-recipes generate` to regenerate from the registry.\n" +
    "// The crypto mechanics here are derived from @webhook-co/webhooks-spec and drift-pinned in CI;\n" +
    "// editing this file directly will fail the drift test.\n\n" +
    'import type { RecipeDescriptor } from "./types";\n\n';
  const body =
    "export const RECIPES: readonly RecipeDescriptor[] = " +
    JSON.stringify(recipes, null, 2) +
    ";\n";
  return header + body;
}
